#!/usr/bin/python
import socket
import os
import sys

s=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
host = "192.168.0.148"
port = 12347
x=0

args = ['client.py','tcp.py','dns.py','http.py']
file_list= ['tcp_output.txt','dns_output.txt','http_output.txt']
try:
	forkpid1 = os.fork()
except OSError as err:
	print "Can't fork the process!\n",err

if forkpid1 != 0:
	forkpid2 = os.fork()
	if forkpid2 != 0:
		forkpid3 = os.fork()
		if forkpid3 != 0:
			child1 = os.wait()[0]
			child2 = os.wait()[0]
			child3 = os.wait()[0]
		elif forkpid3 == 0:
			os.execl("/usr/bin/python",args[0],args[1])
	elif forkpid2 == 0:
		os.execl("/usr/bin/python",args[0],args[3])
elif forkpid1 == 0:
	os.execl("/usr/bin/python",args[0],args[2])

print "Connecting to the server"
s.connect((host,port))
print s.recv(1024)
while x<3:
	f=open(file_list[x],'rb')
	l=f.read(1024)
	while(l):
		s.send(l)
		if not l:break
		l=f.read(1024)
	f.close()
	x=x+1
print "The file is transferred"
s.close()
print "Connection terminate"


	


