#!/usr/bin/python
from progressbar import *
import socket
import sys
import time
import os
from progressbar import ProgressBar
from termcolor import colored

try:
	server = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
except:
	print "Cannot create socket"
	sys.exit(1)

host="192.168.0.9"
port=12347
server.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1)
server.bind((host,port))
server.listen(10)
file_list = ['server.py','tcp_info.py','dns_info.py','http_info.py']
conn,addr = server.accept()
print "Get the connection from ",addr
conn.send("Connect server successfully")	
with open('result.txt','wb') as f:	
	while True:
		l=conn.recv(1024)
		if not l:break
		f.write(l)
	f.close()

print colored("Server received the file","yellow")
time.sleep(1)
print colored("Connection closed!!","red")
conn.close()
server.close()
time.sleep(1)
print "The server is processing data!Wait for 5 second"		
time.sleep(5)

try:
	forkpid1=os.fork()
except OSError as err:
	print "Cannot fork process :",err

if forkpid1 != 0:
	forkpid2 = os.fork()
	if forkpid2 !=0 :
		forkpid3 = os.fork()
		if forkpid3 != 0:
			child1 = os.wait()[0]
			child2 = os.wait()[0]
			child3 = os.wait()[0]
		elif forkpid3 == 0:
			os.execl("/usr/bin/python",file_list[0],file_list[1])
	elif forkpid2 == 0:
		os.execl("/usr/bin/python",file_list[0],file_list[3])
elif forkpid1 == 0:
	os.execl("/usr/bin/python",file_list[0],file_list[2])

cmd = "python filter.py > filter.txt"
os.system(cmd)
print colored("Server is analysing data","cyan")
pbar=ProgressBar()
pbar.start()
for i in pbar(range(100)):
	time.sleep(0.05)
print "Data is analyzed!"

while True:
	answer = raw_input("Do you want to display the result?(y/n) :")
	if answer == 'y':
		result=open('filter.txt').read()
		print result
		print "Finished"
		break
	elif answer == 'n':
		print "See you again"
		break
	print color("Invalid input.Try again","red")


